query users {
  users(order_by: { id: asc }) {
    id
      name
      age
      occupation
      age
      address
      gender
      posts {
        post
        id
        user_id
        created_at
      }
  }
}