import { defineComponent } from '@nuxtjs/composition-api'
import { useQuery, gql } from '@nuxtjs/apollo'

export default defineComponent({
  setup() {
    const { data } = useQuery(gql`
      query {
        users {
          id
          name
          age
        }
      }
    `)

    console.log(data)

    return {}
  },
})